-- Faz 6a: Bildirim — plan §9.10, docs/modules/bildirim.md

CREATE TABLE notification_template (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    notif_type  VARCHAR(24)  NOT NULL,
    channel     VARCHAR(8)   NOT NULL,
    subject     VARCHAR(200),
    body        VARCHAR(2000) NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_notif_template UNIQUE (branch_id, notif_type, channel)
);

CREATE TABLE notification_queue (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT      NOT NULL DEFAULT 0,
    branch_id       BIGINT      NOT NULL DEFAULT 1,
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP   NOT NULL,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP   NOT NULL,
    updated_by      VARCHAR(100),
    party_id        BIGINT,
    to_address      VARCHAR(200)  NOT NULL,
    channel         VARCHAR(8)    NOT NULL,
    notif_type      VARCHAR(24)   NOT NULL,
    subject         VARCHAR(200),
    body            VARCHAR(2000) NOT NULL,
    scheduled_at    TIMESTAMP     NOT NULL,
    status          VARCHAR(10)   NOT NULL DEFAULT 'PENDING',
    attempts        INTEGER       NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP,
    last_error      VARCHAR(500),
    dedup_key       VARCHAR(120)  NOT NULL,
    sent_at         TIMESTAMP,
    CONSTRAINT uq_notif_dedup UNIQUE (dedup_key)
);
CREATE INDEX ix_notif_status_sched ON notification_queue (status, scheduled_at);
