-- Faz 6b: Kartlı Promosyon / Sadakat (PPOS) — plan §9.9, docs/modules/sadakat.md

CREATE TABLE loyalty_program (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           BIGINT      NOT NULL DEFAULT 0,
    branch_id         BIGINT      NOT NULL DEFAULT 1,
    deleted           BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP   NOT NULL,
    created_by        VARCHAR(100),
    updated_at        TIMESTAMP   NOT NULL,
    updated_by        VARCHAR(100),
    name              VARCHAR(100)  NOT NULL,
    earn_rate         NUMERIC(12,4) NOT NULL DEFAULT 0.1000,
    point_to_currency NUMERIC(12,4) NOT NULL DEFAULT 0.0500,
    expiry_months     INTEGER       NOT NULL DEFAULT 12,
    active            BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE TABLE loyalty_card (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        BIGINT      NOT NULL DEFAULT 0,
    branch_id      BIGINT      NOT NULL DEFAULT 1,
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP   NOT NULL,
    created_by     VARCHAR(100),
    updated_at     TIMESTAMP   NOT NULL,
    updated_by     VARCHAR(100),
    card_no        VARCHAR(40)  NOT NULL,
    magnetic_id    VARCHAR(60),
    party_id       BIGINT       NOT NULL,
    program_id     BIGINT       NOT NULL,
    status         VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    points_balance INTEGER      NOT NULL DEFAULT 0,
    issued_at      TIMESTAMP    NOT NULL,
    CONSTRAINT uq_loyalty_card_no UNIQUE (branch_id, card_no)
);
CREATE INDEX ix_loyalty_card_party ON loyalty_card (party_id);
CREATE INDEX ix_loyalty_card_mag ON loyalty_card (magnetic_id);

CREATE TABLE loyalty_transaction (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        BIGINT      NOT NULL DEFAULT 0,
    branch_id      BIGINT      NOT NULL DEFAULT 1,
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP   NOT NULL,
    created_by     VARCHAR(100),
    updated_at     TIMESTAMP   NOT NULL,
    updated_by     VARCHAR(100),
    card_id        BIGINT       NOT NULL,
    txn_type       VARCHAR(14)  NOT NULL,
    points         INTEGER      NOT NULL,
    spend_amount   NUMERIC(19,4),
    currency_value NUMERIC(19,4),
    source_ref     VARCHAR(60),
    at             TIMESTAMP    NOT NULL,
    expires_at     DATE,
    expired        BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_loyalty_txn_card FOREIGN KEY (card_id) REFERENCES loyalty_card (id)
);
CREATE INDEX ix_loyalty_txn_card ON loyalty_transaction (card_id, at);
CREATE INDEX ix_loyalty_txn_expiry ON loyalty_transaction (expires_at, expired);

INSERT INTO loyalty_program (version, branch_id, deleted, created_at, created_by, updated_at, updated_by,
                             name, earn_rate, point_to_currency, expiry_months, active)
VALUES (0, 1, FALSE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system',
        'Standart Sadakat', 0.1000, 0.0500, 12, TRUE);
