-- Faz 8: Banka Ekstresi İçe Aktarma & Mutabakat — plan §10.4, docs/modules/banka-mutabakat.md
-- Dışarıya HTTP yok (CLAUDE.md #1): ekstre dosyası kullanıcı tarafından yüklenir.

CREATE TABLE bank_statement (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           BIGINT       NOT NULL DEFAULT 0,
    branch_id         BIGINT       NOT NULL DEFAULT 1,
    deleted           BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP    NOT NULL,
    created_by        VARCHAR(100),
    updated_at        TIMESTAMP    NOT NULL,
    updated_by        VARCHAR(100),
    fin_account_id    BIGINT       NOT NULL,
    source_format     VARCHAR(10)  NOT NULL,            -- MT940 | CSV
    statement_ref     VARCHAR(60),
    period_start      DATE,
    period_end        DATE,
    opening_balance   NUMERIC(19,4),
    closing_balance   NUMERIC(19,4),
    line_count        INTEGER      NOT NULL DEFAULT 0,
    matched_count     INTEGER      NOT NULL DEFAULT 0,
    original_filename VARCHAR(255),
    imported_at       TIMESTAMP    NOT NULL,
    status            VARCHAR(12)  NOT NULL DEFAULT 'IMPORTED',   -- IMPORTED | RECONCILED
    CONSTRAINT fk_bank_stmt_account FOREIGN KEY (fin_account_id) REFERENCES fin_account (id)
);
CREATE INDEX ix_bank_stmt_account ON bank_statement (fin_account_id, period_end);

CREATE TABLE bank_statement_line (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        BIGINT        NOT NULL DEFAULT 0,
    branch_id      BIGINT        NOT NULL DEFAULT 1,
    deleted        BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP     NOT NULL,
    created_by     VARCHAR(100),
    updated_at     TIMESTAMP     NOT NULL,
    updated_by     VARCHAR(100),
    statement_id   BIGINT        NOT NULL,
    line_no        INTEGER       NOT NULL,
    value_date     DATE          NOT NULL,
    booking_date   DATE,
    amount         NUMERIC(19,4) NOT NULL,              -- İŞARETLİ: + giriş, − çıkış (banka bakışı)
    currency       VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    description    VARCHAR(500),
    counterparty   VARCHAR(200),
    bank_ref       VARCHAR(80),
    raw_line       VARCHAR(1000),
    match_status   VARCHAR(12)   NOT NULL DEFAULT 'UNMATCHED',   -- UNMATCHED | MATCHED | IGNORED | CREATED
    matched_txn_id BIGINT,
    match_score    INTEGER,
    note           VARCHAR(300),
    CONSTRAINT fk_bank_line_stmt FOREIGN KEY (statement_id) REFERENCES bank_statement (id),
    CONSTRAINT uq_bank_line_no UNIQUE (statement_id, line_no)
);
CREATE INDEX ix_bank_line_stmt ON bank_statement_line (statement_id, match_status);
CREATE INDEX ix_bank_line_txn ON bank_statement_line (matched_txn_id);

INSERT INTO setting (version, branch_id, deleted, created_at, created_by, updated_at, updated_by,
                     setting_key, setting_value, description, secret)
VALUES (0, 1, FALSE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system',
        'reconciliation.autoMatchThreshold', '80',
        'Banka mutabakatında otomatik eşleştirme için minimum öneri skoru (0-100)', FALSE);
