-- BeautySalonApp — Faz 0 çekirdek şema
-- H2 v2 (file mode) ve PostgreSQL 16 ile uyumlu taşınabilir DDL.
-- Kural: mevcut migration DÜZENLENMEZ; değişiklik yeni Vxx dosyasıyla yapılır.

-- ---------------------------------------------------------------------------
-- branch : şube / işletme (çok şubeli yapı için; v1'de tek satır, id=1)
-- ---------------------------------------------------------------------------
CREATE TABLE branch (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT       NOT NULL DEFAULT 0,
    branch_id   BIGINT       NOT NULL DEFAULT 1,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP    NOT NULL,
    updated_by  VARCHAR(100),
    code        VARCHAR(20)  NOT NULL,
    title       VARCHAR(200) NOT NULL,
    tax_id      VARCHAR(20),
    address     VARCHAR(400),
    phone       VARCHAR(30),
    is_headquarters BOOLEAN  NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_branch_code UNIQUE (code)
);

INSERT INTO branch (id, version, branch_id, deleted, created_at, created_by, updated_at, updated_by,
                    code, title, is_headquarters)
VALUES (1, 0, 1, FALSE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system',
        'MERKEZ', 'Ana İşletme', TRUE);

-- ---------------------------------------------------------------------------
-- role + role_permission
-- ---------------------------------------------------------------------------
CREATE TABLE role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT       NOT NULL DEFAULT 0,
    branch_id   BIGINT       NOT NULL DEFAULT 1,
    deleted     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP    NOT NULL,
    updated_by  VARCHAR(100),
    name        VARCHAR(40)  NOT NULL,
    description VARCHAR(200),
    system_role BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_role_name UNIQUE (name)
);

CREATE TABLE role_permission (
    role_id     BIGINT       NOT NULL,
    permission  VARCHAR(60)  NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES role (id)
);

-- ---------------------------------------------------------------------------
-- app_user + user_role
-- ---------------------------------------------------------------------------
CREATE TABLE app_user (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version              BIGINT      NOT NULL DEFAULT 0,
    branch_id            BIGINT      NOT NULL DEFAULT 1,
    deleted              BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP   NOT NULL,
    created_by           VARCHAR(100),
    updated_at           TIMESTAMP   NOT NULL,
    updated_by           VARCHAR(100),
    username             VARCHAR(60)  NOT NULL,
    full_name            VARCHAR(120) NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    enabled              BOOLEAN      NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_login_count   INTEGER      NOT NULL DEFAULT 0,
    locked_until         TIMESTAMP,
    last_login_at        TIMESTAMP,
    pin_hash             VARCHAR(100),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE TABLE user_role (
    user_id     BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES role (id)
);

-- ---------------------------------------------------------------------------
-- setting : şube bazlı anahtar-değer
-- ---------------------------------------------------------------------------
CREATE TABLE setting (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT      NOT NULL DEFAULT 0,
    branch_id     BIGINT      NOT NULL DEFAULT 1,
    deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL,
    created_by    VARCHAR(100),
    updated_at    TIMESTAMP   NOT NULL,
    updated_by    VARCHAR(100),
    setting_key   VARCHAR(120) NOT NULL,
    setting_value TEXT,
    description   VARCHAR(300),
    secret        BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_setting_branch_key UNIQUE (branch_id, setting_key)
);

-- ---------------------------------------------------------------------------
-- audit_log : değiştirilemez denetim kaydı (BaseEntity'den türemez)
-- ---------------------------------------------------------------------------
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    at          TIMESTAMP    NOT NULL,
    actor       VARCHAR(100) NOT NULL,
    action      VARCHAR(60)  NOT NULL,
    entity_type VARCHAR(80),
    entity_id   VARCHAR(40),
    branch_id   BIGINT,
    summary     VARCHAR(500),
    detail      TEXT,
    ip          VARCHAR(45)
);
CREATE INDEX ix_audit_at ON audit_log (at);
CREATE INDEX ix_audit_entity ON audit_log (entity_type, entity_id);
CREATE INDEX ix_audit_actor ON audit_log (actor);

-- ---------------------------------------------------------------------------
-- sequence_counter : belge no üretimi (şube x tür x yıl)
-- ---------------------------------------------------------------------------
CREATE TABLE sequence_counter (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id     BIGINT      NOT NULL,
    seq_type      VARCHAR(40) NOT NULL,
    seq_year      INTEGER     NOT NULL,
    current_value BIGINT      NOT NULL DEFAULT 0,
    prefix        VARCHAR(10),
    CONSTRAINT uq_seq UNIQUE (branch_id, seq_type, seq_year)
);

-- ---------------------------------------------------------------------------
-- attachment : dosya ekleri (DB'de yalnızca referans; içerik disk üzerinde)
-- ---------------------------------------------------------------------------
CREATE TABLE attachment (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT      NOT NULL DEFAULT 0,
    branch_id     BIGINT      NOT NULL DEFAULT 1,
    deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL,
    created_by    VARCHAR(100),
    updated_at    TIMESTAMP   NOT NULL,
    updated_by    VARCHAR(100),
    owner_type    VARCHAR(60)  NOT NULL,
    owner_id      BIGINT       NOT NULL,
    file_name     VARCHAR(255) NOT NULL,
    content_type  VARCHAR(100),
    size_bytes    BIGINT,
    storage_path  VARCHAR(500) NOT NULL,
    sha256        VARCHAR(64)
);
CREATE INDEX ix_attachment_owner ON attachment (owner_type, owner_id);

-- ---------------------------------------------------------------------------
-- license_state : imzalı lisans dosyası önbelleği + monotonic clock
-- ---------------------------------------------------------------------------
CREATE TABLE license_state (
    id                             BIGINT PRIMARY KEY,
    license_blob                   TEXT,
    server_status                  VARCHAR(20) DEFAULT 'ACTIVE',
    last_successful_heartbeat_at   TIMESTAMP,
    last_heartbeat_attempt_at      TIMESTAMP,
    consecutive_heartbeat_failures INTEGER      DEFAULT 0,
    max_seen_time_enc              VARCHAR(512),
    read_only_since                TIMESTAMP,
    tamper_flag                    BOOLEAN      NOT NULL DEFAULT FALSE
);
INSERT INTO license_state (id, server_status, consecutive_heartbeat_failures, tamper_flag)
VALUES (1, 'ACTIVE', 0, FALSE);
