-- Modül: Cari (müşteri / satıcı / personel / perakende) — plan §9.2, docs/modules/cari.md

CREATE TABLE party (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT      NOT NULL DEFAULT 0,
    branch_id             BIGINT      NOT NULL DEFAULT 1,
    deleted               BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMP   NOT NULL,
    created_by            VARCHAR(100),
    updated_at            TIMESTAMP   NOT NULL,
    updated_by            VARCHAR(100),
    party_type            VARCHAR(20)  NOT NULL,
    code                  VARCHAR(30)  NOT NULL,
    title                 VARCHAR(200) NOT NULL,
    first_name            VARCHAR(100),
    last_name             VARCHAR(100),
    tax_id                VARCHAR(200),           -- şifreli
    tc_no                 VARCHAR(200),           -- şifreli
    phone                 VARCHAR(200),           -- şifreli
    phone_bi              VARCHAR(32),            -- blind index (arama)
    email                 VARCHAR(300),           -- şifreli
    birth_date            DATE,
    wedding_anniversary   DATE,
    gender                VARCHAR(10),
    notes                 VARCHAR(1000),
    sms_consent           BOOLEAN      NOT NULL DEFAULT FALSE,
    email_consent         BOOLEAN      NOT NULL DEFAULT FALSE,
    iys_status            VARCHAR(15)  NOT NULL DEFAULT 'BILINMIYOR',
    consent_date          TIMESTAMP,
    risk_limit            NUMERIC(19,4),
    default_discount_rate NUMERIC(19,4) NOT NULL DEFAULT 0,
    price_list_id         BIGINT,
    anonymized            BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_party_code UNIQUE (branch_id, code)
);
CREATE INDEX ix_party_type ON party (party_type);
CREATE INDEX ix_party_phone_bi ON party (phone_bi);
CREATE INDEX ix_party_name ON party (title);

CREATE TABLE party_address (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    party_id    BIGINT       NOT NULL,
    label       VARCHAR(60),
    address     VARCHAR(400) NOT NULL,
    city        VARCHAR(60),
    district    VARCHAR(60),
    postcode    VARCHAR(12),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_party_address_party FOREIGN KEY (party_id) REFERENCES party (id)
);
CREATE INDEX ix_party_address_party ON party_address (party_id);

CREATE TABLE party_note (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    party_id    BIGINT       NOT NULL,
    category    VARCHAR(20)  NOT NULL DEFAULT 'GENEL',
    note_text   TEXT         NOT NULL,          -- şifreli (özel nitelikli veri)
    pinned      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_party_note_party FOREIGN KEY (party_id) REFERENCES party (id)
);
CREATE INDEX ix_party_note_party ON party_note (party_id);

CREATE TABLE party_account (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT      NOT NULL DEFAULT 0,
    branch_id       BIGINT      NOT NULL DEFAULT 1,
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP   NOT NULL,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP   NOT NULL,
    updated_by      VARCHAR(100),
    party_id        BIGINT       NOT NULL,
    account_kind    VARCHAR(10)  NOT NULL DEFAULT 'NORMAL',
    currency        VARCHAR(3)   NOT NULL DEFAULT 'TRY',
    opening_balance NUMERIC(19,4) NOT NULL DEFAULT 0,
    CONSTRAINT fk_party_account_party FOREIGN KEY (party_id) REFERENCES party (id),
    CONSTRAINT uq_party_account UNIQUE (party_id, account_kind, currency)
);
CREATE INDEX ix_party_account_party ON party_account (party_id);

CREATE TABLE party_transaction (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    account_id  BIGINT       NOT NULL,
    txn_date    DATE         NOT NULL,
    doc_type    VARCHAR(24)  NOT NULL,
    doc_ref     VARCHAR(40),
    line_key    VARCHAR(60),
    description VARCHAR(300),
    debit       NUMERIC(19,4) NOT NULL DEFAULT 0,
    credit      NUMERIC(19,4) NOT NULL DEFAULT 0,
    currency    VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    reverses_id BIGINT,
    CONSTRAINT fk_party_txn_account FOREIGN KEY (account_id) REFERENCES party_account (id)
);
CREATE INDEX ix_party_txn_account ON party_transaction (account_id, txn_date);
CREATE INDEX ix_party_txn_doc ON party_transaction (doc_type, doc_ref);
CREATE UNIQUE INDEX uq_party_txn_idem ON party_transaction (doc_type, doc_ref, line_key);
