-- Modül: Stok — plan §9.3, docs/modules/stok.md
-- Tüm miktarlar base unit cinsinden (NUMERIC 19,6). Maliyet base birim başına (NUMERIC 19,4).

CREATE TABLE unit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(60)  NOT NULL,
    CONSTRAINT uq_unit_code UNIQUE (branch_id, code)
);

CREATE TABLE item_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    parent_id   BIGINT,
    name        VARCHAR(120) NOT NULL
);

CREATE TABLE item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT      NOT NULL DEFAULT 0,
    branch_id    BIGINT      NOT NULL DEFAULT 1,
    deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP   NOT NULL,
    created_by   VARCHAR(100),
    updated_at   TIMESTAMP   NOT NULL,
    updated_by   VARCHAR(100),
    code         VARCHAR(40)  NOT NULL,
    name         VARCHAR(200) NOT NULL,
    item_type    VARCHAR(10)  NOT NULL DEFAULT 'EMTIA',
    vat_rate     NUMERIC(5,2) NOT NULL DEFAULT 20.00,
    base_unit_id BIGINT       NOT NULL,
    category_id  BIGINT,
    brand        VARCHAR(100),
    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    reorder_level NUMERIC(19,6),
    CONSTRAINT uq_item_code UNIQUE (branch_id, code),
    CONSTRAINT fk_item_base_unit FOREIGN KEY (base_unit_id) REFERENCES unit (id)
);
CREATE INDEX ix_item_name ON item (name);
CREATE INDEX ix_item_category ON item (category_id);

CREATE TABLE item_unit (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    item_id     BIGINT        NOT NULL,
    unit_id     BIGINT        NOT NULL,
    factor      NUMERIC(19,6) NOT NULL DEFAULT 1,
    sale_price  NUMERIC(19,4),
    is_base     BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_item_unit UNIQUE (item_id, unit_id),
    CONSTRAINT fk_item_unit_item FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT fk_item_unit_unit FOREIGN KEY (unit_id) REFERENCES unit (id)
);
CREATE INDEX ix_item_unit_item ON item_unit (item_id);

CREATE TABLE item_barcode (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    item_id     BIGINT       NOT NULL,
    barcode     VARCHAR(64)  NOT NULL,
    unit_id     BIGINT       NOT NULL,
    is_primary  BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_item_barcode UNIQUE (branch_id, barcode),
    CONSTRAINT fk_item_barcode_item FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT fk_item_barcode_unit FOREIGN KEY (unit_id) REFERENCES unit (id)
);
CREATE INDEX ix_item_barcode_item ON item_barcode (item_id);

CREATE TABLE warehouse (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    wh_type     VARCHAR(15)  NOT NULL DEFAULT 'WAREHOUSE',
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_warehouse_code UNIQUE (branch_id, code)
);

CREATE TABLE stock_movement (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        BIGINT      NOT NULL DEFAULT 0,
    branch_id      BIGINT      NOT NULL DEFAULT 1,
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP   NOT NULL,
    created_by     VARCHAR(100),
    updated_at     TIMESTAMP   NOT NULL,
    updated_by     VARCHAR(100),
    mv_date        DATE          NOT NULL,
    item_id        BIGINT        NOT NULL,
    warehouse_id   BIGINT        NOT NULL,
    direction      VARCHAR(3)    NOT NULL,
    base_qty       NUMERIC(19,6) NOT NULL,
    entered_unit_id BIGINT       NOT NULL,
    entered_qty    NUMERIC(19,6) NOT NULL,
    unit_cost      NUMERIC(19,4) NOT NULL DEFAULT 0,
    doc_type       VARCHAR(20)   NOT NULL,
    doc_ref        VARCHAR(40),
    line_key       VARCHAR(60),
    note           VARCHAR(300),
    CONSTRAINT fk_stock_mv_item FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT fk_stock_mv_wh FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)
);
CREATE INDEX ix_stock_mv_item_wh ON stock_movement (item_id, warehouse_id, mv_date);
CREATE INDEX ix_stock_mv_doc ON stock_movement (doc_type, doc_ref);
CREATE UNIQUE INDEX uq_stock_mv_idem ON stock_movement (doc_type, doc_ref, line_key);

CREATE TABLE stock_level (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT      NOT NULL DEFAULT 0,
    branch_id     BIGINT      NOT NULL DEFAULT 1,
    deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL,
    created_by    VARCHAR(100),
    updated_at    TIMESTAMP   NOT NULL,
    updated_by    VARCHAR(100),
    item_id       BIGINT        NOT NULL,
    warehouse_id  BIGINT        NOT NULL,
    qty_base      NUMERIC(19,6) NOT NULL DEFAULT 0,
    avg_cost      NUMERIC(19,4) NOT NULL DEFAULT 0,
    CONSTRAINT uq_stock_level UNIQUE (item_id, warehouse_id),
    CONSTRAINT fk_stock_level_item FOREIGN KEY (item_id) REFERENCES item (id),
    CONSTRAINT fk_stock_level_wh FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)
);

INSERT INTO setting (version, branch_id, deleted, created_at, created_by, updated_at, updated_by,
                     setting_key, setting_value, description, secret)
VALUES (0, 1, FALSE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system',
        'stock.negativeStock.mode', 'WARN', 'Negatif stok politikası: ALLOW | WARN | BLOCK', FALSE);
