-- Modül: Kasa & Gelir-Gider — plan §9.5, docs/modules/finans.md

CREATE TABLE fin_account (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version               BIGINT      NOT NULL DEFAULT 0,
    branch_id             BIGINT      NOT NULL DEFAULT 1,
    deleted               BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMP   NOT NULL,
    created_by            VARCHAR(100),
    updated_at            TIMESTAMP   NOT NULL,
    updated_by            VARCHAR(100),
    code                  VARCHAR(20)  NOT NULL,
    name                  VARCHAR(120) NOT NULL,
    kind                  VARCHAR(10)  NOT NULL,
    currency              VARCHAR(3)   NOT NULL DEFAULT 'TRY',
    opening_balance       NUMERIC(19,4) NOT NULL DEFAULT 0,
    is_commission_bearing BOOLEAN      NOT NULL DEFAULT FALSE,
    commission_rate       NUMERIC(7,4),
    bank_info             VARCHAR(300),
    is_default            BOOLEAN      NOT NULL DEFAULT FALSE,
    active                BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_fin_account_code UNIQUE (branch_id, code)
);

CREATE TABLE income_expense_card (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        BIGINT      NOT NULL DEFAULT 0,
    branch_id      BIGINT      NOT NULL DEFAULT 1,
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP   NOT NULL,
    created_by     VARCHAR(100),
    updated_at     TIMESTAMP   NOT NULL,
    updated_by     VARCHAR(100),
    parent_id      BIGINT,
    code           VARCHAR(30)  NOT NULL,
    name           VARCHAR(150) NOT NULL,
    direction      VARCHAR(8)   NOT NULL,
    budget_amount  NUMERIC(19,4),
    is_service_card BOOLEAN     NOT NULL DEFAULT FALSE,
    postable       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_ie_card_code UNIQUE (branch_id, code)
);

CREATE TABLE cash_transaction (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                BIGINT      NOT NULL DEFAULT 0,
    branch_id              BIGINT      NOT NULL DEFAULT 1,
    deleted                BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMP   NOT NULL,
    created_by             VARCHAR(100),
    updated_at             TIMESTAMP   NOT NULL,
    updated_by             VARCHAR(100),
    txn_type               VARCHAR(12)  NOT NULL,
    txn_date               DATE         NOT NULL,
    account_id             BIGINT       NOT NULL,
    counter_account_id     BIGINT,
    party_account_id       BIGINT,
    income_expense_card_id BIGINT,
    amount                 NUMERIC(19,4) NOT NULL,
    currency               VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    fx_rate                NUMERIC(19,6),
    description            VARCHAR(300),
    doc_no                 VARCHAR(40),
    doc_type               VARCHAR(20),
    doc_ref                VARCHAR(40),
    line_key               VARCHAR(60),
    voided                 BOOLEAN      NOT NULL DEFAULT FALSE,
    void_reason            VARCHAR(300),
    reverses_id            BIGINT,
    CONSTRAINT fk_cash_txn_account FOREIGN KEY (account_id) REFERENCES fin_account (id)
);
CREATE INDEX ix_cash_txn_account ON cash_transaction (account_id, txn_date);
CREATE INDEX ix_cash_txn_doc ON cash_transaction (doc_type, doc_ref);
CREATE INDEX ix_cash_txn_card ON cash_transaction (income_expense_card_id);
