-- Modül: Satış Sözleşmesi + Otomatik Taksitlendirme — plan §9.8, docs/modules (cari/finans ile entegre)

CREATE TABLE sales_contract (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version            BIGINT      NOT NULL DEFAULT 0,
    branch_id          BIGINT      NOT NULL DEFAULT 1,
    deleted            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP   NOT NULL,
    created_by         VARCHAR(100),
    updated_at         TIMESTAMP   NOT NULL,
    updated_by         VARCHAR(100),
    doc_no             VARCHAR(40)  NOT NULL,
    party_id           BIGINT       NOT NULL,
    party_account_id   BIGINT       NOT NULL,
    contract_date      DATE          NOT NULL,
    total_amount       NUMERIC(19,4) NOT NULL,
    down_payment       NUMERIC(19,4) NOT NULL DEFAULT 0,
    installment_count  INTEGER       NOT NULL,
    first_due_date     DATE          NOT NULL,
    period             VARCHAR(10)   NOT NULL DEFAULT 'AYLIK',
    interest_rate      NUMERIC(7,4)  NOT NULL DEFAULT 0,
    currency           VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    status             VARCHAR(12)   NOT NULL DEFAULT 'ACTIVE',
    signed_document_id BIGINT,
    notes              VARCHAR(1000),
    cancel_reason      VARCHAR(300),
    CONSTRAINT uq_contract_doc_no UNIQUE (branch_id, doc_no)
);
CREATE INDEX ix_contract_party ON sales_contract (party_id);

CREATE TABLE contract_line (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT      NOT NULL DEFAULT 0,
    branch_id     BIGINT      NOT NULL DEFAULT 1,
    deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL,
    created_by    VARCHAR(100),
    updated_at    TIMESTAMP   NOT NULL,
    updated_by    VARCHAR(100),
    contract_id   BIGINT        NOT NULL,
    item_id       BIGINT,
    description   VARCHAR(300)  NOT NULL,
    quantity      NUMERIC(19,4) NOT NULL DEFAULT 1,
    session_count INTEGER,
    session_used  INTEGER       NOT NULL DEFAULT 0,
    unit_price    NUMERIC(19,4) NOT NULL,
    line_total    NUMERIC(19,4) NOT NULL,
    CONSTRAINT fk_contract_line_contract FOREIGN KEY (contract_id) REFERENCES sales_contract (id)
);
CREATE INDEX ix_contract_line_contract ON contract_line (contract_id);

CREATE TABLE installment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    contract_id BIGINT        NOT NULL,
    seq         INTEGER       NOT NULL,
    due_date    DATE          NOT NULL,
    amount      NUMERIC(19,4) NOT NULL,
    paid_amount NUMERIC(19,4) NOT NULL DEFAULT 0,
    paid_at     TIMESTAMP,
    status      VARCHAR(10)   NOT NULL DEFAULT 'BEKLIYOR',
    CONSTRAINT uq_installment_seq UNIQUE (contract_id, seq),
    CONSTRAINT fk_installment_contract FOREIGN KEY (contract_id) REFERENCES sales_contract (id)
);
CREATE INDEX ix_installment_due ON installment (due_date, status);
