-- Modül: Frondex Randevu — plan §9.7, docs/modules/randevu.md
-- Zaman değerleri UTC (TIMESTAMP, Instant).

CREATE TABLE service_definition (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version           BIGINT      NOT NULL DEFAULT 0,
    branch_id         BIGINT      NOT NULL DEFAULT 1,
    deleted           BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP   NOT NULL,
    created_by        VARCHAR(100),
    updated_at        TIMESTAMP   NOT NULL,
    updated_by        VARCHAR(100),
    code              VARCHAR(30)  NOT NULL,
    name              VARCHAR(150) NOT NULL,
    duration_min      INTEGER      NOT NULL DEFAULT 30,
    buffer_before_min INTEGER      NOT NULL DEFAULT 0,
    buffer_after_min  INTEGER      NOT NULL DEFAULT 0,
    price             NUMERIC(19,4) NOT NULL DEFAULT 0,
    vat_rate          NUMERIC(5,2)  NOT NULL DEFAULT 20.00,
    resource_required BOOLEAN      NOT NULL DEFAULT FALSE,
    stock_item_id     BIGINT,
    income_card_id    BIGINT,
    active            BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_service_code UNIQUE (branch_id, code)
);

CREATE TABLE service_recipe (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    service_id  BIGINT        NOT NULL,
    item_id     BIGINT        NOT NULL,
    unit_id     BIGINT        NOT NULL,
    quantity    NUMERIC(19,6) NOT NULL,
    CONSTRAINT fk_service_recipe_service FOREIGN KEY (service_id) REFERENCES service_definition (id)
);
CREATE INDEX ix_service_recipe_service ON service_recipe (service_id);

CREATE TABLE resource (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    res_type    VARCHAR(12)  NOT NULL DEFAULT 'ODA',
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_resource_code UNIQUE (branch_id, code)
);

CREATE TABLE staff_shift (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        BIGINT      NOT NULL DEFAULT 0,
    branch_id      BIGINT      NOT NULL DEFAULT 1,
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP   NOT NULL,
    created_by     VARCHAR(100),
    updated_at     TIMESTAMP   NOT NULL,
    updated_by     VARCHAR(100),
    staff_party_id BIGINT      NOT NULL,
    shift_date     DATE        NOT NULL,
    start_time     TIME,
    end_time       TIME,
    shift_type     VARCHAR(8)  NOT NULL DEFAULT 'WORK',
    note           VARCHAR(200)
);
CREATE INDEX ix_staff_shift ON staff_shift (staff_party_id, shift_date);

CREATE TABLE appointment (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version         BIGINT      NOT NULL DEFAULT 0,
    branch_id       BIGINT      NOT NULL DEFAULT 1,
    deleted         BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP   NOT NULL,
    created_by      VARCHAR(100),
    updated_at      TIMESTAMP   NOT NULL,
    updated_by      VARCHAR(100),
    party_id        BIGINT       NOT NULL,
    staff_party_id  BIGINT       NOT NULL,
    resource_id     BIGINT,
    service_id      BIGINT       NOT NULL,
    start_at        TIMESTAMP    NOT NULL,
    end_at          TIMESTAMP    NOT NULL,
    status          VARCHAR(12)  NOT NULL DEFAULT 'PLANLANDI',
    source          VARCHAR(10)  NOT NULL DEFAULT 'YERINDE',
    notes           VARCHAR(500),
    price_snapshot  NUMERIC(19,4) NOT NULL DEFAULT 0,
    reminder_sent_at TIMESTAMP,
    arrived_at      TIMESTAMP,
    no_show         BOOLEAN      NOT NULL DEFAULT FALSE,
    contract_line_id BIGINT,
    chain_done      BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_appt_service FOREIGN KEY (service_id) REFERENCES service_definition (id)
);
CREATE INDEX ix_appt_staff_time ON appointment (staff_party_id, start_at);
CREATE INDEX ix_appt_resource_time ON appointment (resource_id, start_at);
CREATE INDEX ix_appt_party ON appointment (party_id);
CREATE INDEX ix_appt_time ON appointment (start_at);

INSERT INTO setting (version, branch_id, deleted, created_at, created_by, updated_at, updated_by,
                     setting_key, setting_value, description, secret)
VALUES (0, 1, FALSE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system',
        'appointment.autoConsumeRecipe', 'true',
        'Randevu GELDI işaretlenince hizmet reçetesindeki stoklar otomatik sarf edilsin', FALSE);
