-- Faz 4a: Fatura + Çek + POS — plan §9.6, §10.5, §10.7

CREATE TABLE invoice (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                  BIGINT      NOT NULL DEFAULT 0,
    branch_id                BIGINT      NOT NULL DEFAULT 1,
    deleted                  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMP   NOT NULL,
    created_by               VARCHAR(100),
    updated_at               TIMESTAMP   NOT NULL,
    updated_by               VARCHAR(100),
    invoice_type             VARCHAR(12)  NOT NULL,
    series                   VARCHAR(10),
    doc_no                   VARCHAR(40)  NOT NULL,
    invoice_date             DATE          NOT NULL,
    party_id                 BIGINT        NOT NULL,
    party_account_id         BIGINT        NOT NULL,
    warehouse_id             BIGINT,
    currency                 VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    fx_rate                  NUMERIC(19,6),
    cash_register_receipt_no VARCHAR(40),
    subtotal                 NUMERIC(19,4) NOT NULL DEFAULT 0,
    discount_total           NUMERIC(19,4) NOT NULL DEFAULT 0,
    vat_total                NUMERIC(19,4) NOT NULL DEFAULT 0,
    grand_total              NUMERIC(19,4) NOT NULL DEFAULT 0,
    status                   VARCHAR(10)   NOT NULL DEFAULT 'CONFIRMED',
    notes                    VARCHAR(500),
    void_reason              VARCHAR(300),
    einvoice_uuid            VARCHAR(64),
    einvoice_status          VARCHAR(20),
    CONSTRAINT uq_invoice_doc_no UNIQUE (branch_id, doc_no)
);
CREATE INDEX ix_invoice_party ON invoice (party_id);
CREATE INDEX ix_invoice_type_date ON invoice (invoice_type, invoice_date);

CREATE TABLE invoice_line (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT      NOT NULL DEFAULT 0,
    branch_id    BIGINT      NOT NULL DEFAULT 1,
    deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP   NOT NULL,
    created_by   VARCHAR(100),
    updated_at   TIMESTAMP   NOT NULL,
    updated_by   VARCHAR(100),
    invoice_id   BIGINT        NOT NULL,
    line_no      INTEGER       NOT NULL,
    item_id      BIGINT,
    is_service   BOOLEAN       NOT NULL DEFAULT FALSE,
    description  VARCHAR(300)  NOT NULL,
    quantity     NUMERIC(19,6) NOT NULL,
    unit_id      BIGINT,
    unit_price   NUMERIC(19,4) NOT NULL,
    discount_rate NUMERIC(7,4) NOT NULL DEFAULT 0,
    vat_rate     NUMERIC(5,2)  NOT NULL DEFAULT 0,
    line_net     NUMERIC(19,4) NOT NULL,
    line_vat     NUMERIC(19,4) NOT NULL,
    line_total   NUMERIC(19,4) NOT NULL,
    CONSTRAINT fk_invoice_line_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id)
);
CREATE INDEX ix_invoice_line_invoice ON invoice_line (invoice_id);

CREATE TABLE invoice_payment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    invoice_id  BIGINT        NOT NULL,
    method      VARCHAR(10)   NOT NULL,
    amount      NUMERIC(19,4) NOT NULL,
    account_id  BIGINT,
    cheque_id   BIGINT,
    pos_slip_id BIGINT,
    CONSTRAINT fk_invoice_payment_invoice FOREIGN KEY (invoice_id) REFERENCES invoice (id)
);
CREATE INDEX ix_invoice_payment_invoice ON invoice_payment (invoice_id);

CREATE TABLE cheque (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version            BIGINT      NOT NULL DEFAULT 0,
    branch_id          BIGINT      NOT NULL DEFAULT 1,
    deleted            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP   NOT NULL,
    created_by         VARCHAR(100),
    updated_at         TIMESTAMP   NOT NULL,
    updated_by         VARCHAR(100),
    cheque_no          VARCHAR(40)  NOT NULL,
    cheque_type        VARCHAR(12)  NOT NULL,
    bank_name          VARCHAR(120),
    drawer             VARCHAR(150),
    due_date           DATE          NOT NULL,
    amount             NUMERIC(19,4) NOT NULL,
    currency           VARCHAR(3)    NOT NULL DEFAULT 'TRY',
    party_account_id   BIGINT,
    status             VARCHAR(16)   NOT NULL DEFAULT 'PORTFOYDE',
    settled_account_id BIGINT,
    source_doc         VARCHAR(40),
    note               VARCHAR(300)
);
CREATE INDEX ix_cheque_party ON cheque (party_account_id);
CREATE INDEX ix_cheque_due ON cheque (due_date, status);

CREATE TABLE cheque_movement (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cheque_id   BIGINT       NOT NULL,
    at          TIMESTAMP    NOT NULL,
    from_status VARCHAR(16),
    to_status   VARCHAR(16)  NOT NULL,
    actor       VARCHAR(100),
    note        VARCHAR(300)
);
CREATE INDEX ix_cheque_mv ON cheque_movement (cheque_id, at);

CREATE TABLE pos_slip (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version            BIGINT      NOT NULL DEFAULT 0,
    branch_id          BIGINT      NOT NULL DEFAULT 1,
    deleted            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at         TIMESTAMP   NOT NULL,
    created_by         VARCHAR(100),
    updated_at         TIMESTAMP   NOT NULL,
    updated_by         VARCHAR(100),
    pos_account_id     BIGINT        NOT NULL,
    bank_account_id    BIGINT,
    slip_no            VARCHAR(40),
    slip_date          DATE          NOT NULL,
    amount             NUMERIC(19,4) NOT NULL,
    installment_count  INTEGER       NOT NULL DEFAULT 1,
    commission_rate    NUMERIC(7,4)  NOT NULL DEFAULT 0,
    commission_amount  NUMERIC(19,4) NOT NULL DEFAULT 0,
    net_amount         NUMERIC(19,4) NOT NULL DEFAULT 0,
    value_date         DATE,
    settled            BOOLEAN       NOT NULL DEFAULT FALSE,
    source_doc         VARCHAR(40)
);
CREATE INDEX ix_pos_slip_settled ON pos_slip (settled, value_date);

INSERT INTO setting (version, branch_id, deleted, created_at, created_by, updated_at, updated_by,
                     setting_key, setting_value, description, secret)
VALUES (0, 1, FALSE, CURRENT_TIMESTAMP, 'system', CURRENT_TIMESTAMP, 'system',
        'invoice.retail.requireReceiptNo', 'false',
        'Perakende faturada yazarkasa fiş numarası zorunlu olsun', FALSE);
