-- Faz 4b: Personel + Prim — plan §9.4, docs/modules/personel.md

CREATE TABLE staff_class (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version      BIGINT      NOT NULL DEFAULT 0,
    branch_id    BIGINT      NOT NULL DEFAULT 1,
    deleted      BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP   NOT NULL,
    created_by   VARCHAR(100),
    updated_at   TIMESTAMP   NOT NULL,
    updated_by   VARCHAR(100),
    name         VARCHAR(80)  NOT NULL,
    description  VARCHAR(200),
    service_rate NUMERIC(7,4),
    product_rate NUMERIC(7,4),
    CONSTRAINT uq_staff_class_name UNIQUE (branch_id, name)
);

CREATE TABLE staff (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version              BIGINT      NOT NULL DEFAULT 0,
    branch_id            BIGINT      NOT NULL DEFAULT 1,
    deleted              BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP   NOT NULL,
    created_by           VARCHAR(100),
    updated_at           TIMESTAMP   NOT NULL,
    updated_by           VARCHAR(100),
    party_id             BIGINT       NOT NULL,
    title                VARCHAR(100),
    hire_date            DATE,
    iban                 VARCHAR(200),        -- şifreli
    staff_class_id       BIGINT,
    default_service_rate NUMERIC(7,4),
    default_product_rate NUMERIC(7,4),
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_staff_party UNIQUE (party_id)
);

CREATE TABLE commission_rule (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version        BIGINT      NOT NULL DEFAULT 0,
    branch_id      BIGINT      NOT NULL DEFAULT 1,
    deleted        BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMP   NOT NULL,
    created_by     VARCHAR(100),
    updated_at     TIMESTAMP   NOT NULL,
    updated_by     VARCHAR(100),
    scope          VARCHAR(10)   NOT NULL,
    staff_id       BIGINT,
    staff_class_id BIGINT,
    basis          VARCHAR(8)    NOT NULL DEFAULT 'RATE',
    rule_value     NUMERIC(19,4) NOT NULL DEFAULT 0,
    min_revenue    NUMERIC(19,4),
    active         BOOLEAN       NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_commission_rule_scope ON commission_rule (scope, active);

CREATE TABLE staff_commission (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    staff_id    BIGINT        NOT NULL,
    period_ym   VARCHAR(7)    NOT NULL,
    source_type VARCHAR(16)   NOT NULL,
    source_ref  VARCHAR(60)   NOT NULL,
    base_amount NUMERIC(19,4) NOT NULL,
    rate        NUMERIC(19,4),
    amount      NUMERIC(19,4) NOT NULL,
    status      VARCHAR(10)   NOT NULL DEFAULT 'TAHAKKUK',
    accrued_at  TIMESTAMP     NOT NULL,
    paid_at     TIMESTAMP,
    CONSTRAINT uq_staff_commission_src UNIQUE (staff_id, source_type, source_ref)
);
CREATE INDEX ix_staff_commission_period ON staff_commission (staff_id, period_ym, status);

CREATE TABLE staff_advance (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version       BIGINT      NOT NULL DEFAULT 0,
    branch_id     BIGINT      NOT NULL DEFAULT 1,
    deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMP   NOT NULL,
    created_by    VARCHAR(100),
    updated_at    TIMESTAMP   NOT NULL,
    updated_by    VARCHAR(100),
    staff_id      BIGINT        NOT NULL,
    adv_date      DATE          NOT NULL,
    amount        NUMERIC(19,4) NOT NULL,
    account_id    BIGINT        NOT NULL,
    closed_period VARCHAR(7),
    doc_no        VARCHAR(40)
);
CREATE INDEX ix_staff_advance_staff ON staff_advance (staff_id);

CREATE TABLE salary_period (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version     BIGINT      NOT NULL DEFAULT 0,
    branch_id   BIGINT      NOT NULL DEFAULT 1,
    deleted     BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP   NOT NULL,
    created_by  VARCHAR(100),
    updated_at  TIMESTAMP   NOT NULL,
    updated_by  VARCHAR(100),
    staff_id    BIGINT        NOT NULL,
    period_ym   VARCHAR(7)    NOT NULL,
    gross       NUMERIC(19,4) NOT NULL DEFAULT 0,
    deductions  NUMERIC(19,4) NOT NULL DEFAULT 0,
    net         NUMERIC(19,4) NOT NULL DEFAULT 0,
    locked      BOOLEAN       NOT NULL DEFAULT FALSE,
    paid_at     TIMESTAMP,
    CONSTRAINT uq_salary_period UNIQUE (staff_id, period_ym)
);
