-- Faz 5: Yedekleme kayıt defteri — plan §11

CREATE TABLE backup_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        VARCHAR(12)  NOT NULL,
    trigger_src VARCHAR(20),
    started_at  TIMESTAMP    NOT NULL,
    finished_at TIMESTAMP,
    status      VARCHAR(10)  NOT NULL DEFAULT 'RUNNING',
    file_path   VARCHAR(500),
    size_bytes  BIGINT,
    checksum    VARCHAR(64),
    verified_at TIMESTAMP,
    error       VARCHAR(1000),
    actor       VARCHAR(100)
);
CREATE INDEX ix_backup_log_started ON backup_log (started_at);
