-- Lisans sunucusu şeması (§6.8). H2 + PostgreSQL uyumlu.

CREATE TABLE customer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    tax_id     VARCHAR(20),
    email      VARCHAR(200),
    phone      VARCHAR(30),
    notes      VARCHAR(1000),
    created_at TIMESTAMP    NOT NULL
);

CREATE TABLE subscription (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT       NOT NULL,
    plan         VARCHAR(12)  NOT NULL DEFAULT 'PRO',
    status       VARCHAR(16)  NOT NULL DEFAULT 'PENDING_PAYMENT',
    monthly_fee  NUMERIC(12,2) DEFAULT 0,
    start_date   DATE         NOT NULL,
    paid_through DATE         NOT NULL,
    grace_days   INTEGER      NOT NULL DEFAULT 7,
    created_at   TIMESTAMP    NOT NULL,
    CONSTRAINT fk_subscription_customer FOREIGN KEY (customer_id) REFERENCES customer (id)
);

CREATE TABLE license (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id       VARCHAR(24)  NOT NULL,
    activation_key   VARCHAR(32)  NOT NULL,
    customer_id      BIGINT       NOT NULL,
    subscription_id  BIGINT       NOT NULL,
    plan             VARCHAR(12)  NOT NULL,
    modules          VARCHAR(500) NOT NULL,
    max_terminals    INTEGER      NOT NULL DEFAULT 1,
    max_branches     INTEGER      NOT NULL DEFAULT 1,
    max_active_users INTEGER      NOT NULL DEFAULT 5,
    max_customers    INTEGER,
    grace_days       INTEGER      NOT NULL DEFAULT 7,
    offline_mode     BOOLEAN      NOT NULL DEFAULT FALSE,
    status           VARCHAR(16)  NOT NULL DEFAULT 'UNACTIVATED',
    not_after        TIMESTAMP,
    not_before       TIMESTAMP,
    issued_at        TIMESTAMP,
    last_renewed_at  TIMESTAMP,
    activated_at     TIMESTAMP,
    note             VARCHAR(300),
    CONSTRAINT uq_license_license_id UNIQUE (license_id),
    CONSTRAINT uq_license_activation_key UNIQUE (activation_key),
    CONSTRAINT fk_license_customer FOREIGN KEY (customer_id) REFERENCES customer (id),
    CONSTRAINT fk_license_subscription FOREIGN KEY (subscription_id) REFERENCES subscription (id)
);

CREATE TABLE license_binding (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id  VARCHAR(24)  NOT NULL,
    fingerprint VARCHAR(128) NOT NULL,
    fp_version  INTEGER      NOT NULL DEFAULT 2,
    bound_at    TIMESTAMP    NOT NULL,
    last_seen_at TIMESTAMP,
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);
CREATE INDEX ix_binding_license ON license_binding (license_id);

CREATE TABLE heartbeat_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id      VARCHAR(24) NOT NULL,
    fingerprint     VARCHAR(128),
    app_version     VARCHAR(40),
    os              VARCHAR(120),
    received_at     TIMESTAMP   NOT NULL,
    response_status VARCHAR(16),
    nonce           VARCHAR(64),
    remote_ip       VARCHAR(200)
);
CREATE INDEX ix_hb_license ON heartbeat_log (license_id, received_at);

CREATE TABLE transfer_request (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    license_id      VARCHAR(24)  NOT NULL,
    old_fingerprint VARCHAR(128),
    new_fingerprint VARCHAR(128) NOT NULL,
    status          VARCHAR(10)  NOT NULL DEFAULT 'PENDING',
    auto_approved   BOOLEAN      NOT NULL DEFAULT FALSE,
    requested_at    TIMESTAMP    NOT NULL,
    decided_at      TIMESTAMP,
    decided_by      VARCHAR(100)
);
CREATE INDEX ix_transfer_license ON transfer_request (license_id);

CREATE TABLE payment_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subscription_id BIGINT        NOT NULL,
    amount          NUMERIC(12,2) NOT NULL,
    period_start    DATE          NOT NULL,
    period_end      DATE          NOT NULL,
    method          VARCHAR(40),
    paid_at         TIMESTAMP     NOT NULL,
    marked_by       VARCHAR(100)
);
CREATE INDEX ix_payment_sub ON payment_record (subscription_id);

CREATE TABLE app_release (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel     VARCHAR(20)  NOT NULL DEFAULT 'stable',
    version     VARCHAR(20)  NOT NULL,
    url         VARCHAR(400) NOT NULL,
    checksum    VARCHAR(128),
    mandatory   BOOLEAN      NOT NULL DEFAULT FALSE,
    released_at TIMESTAMP    NOT NULL,
    notes       VARCHAR(1000)
);
CREATE INDEX ix_release_channel ON app_release (channel, released_at);
